### ISSUE TITLE
behavior of step! with tstop

### ISSUE THREAD

**Issue by slwu89** [SciML/DelayDiffEq.jl#188]
I have a question regarding the behavior of stepping, particularly about `advance_to_tstop` , in this part of the docs: https://diffeq.sciml.ai/stable/basics/integrator/#Additional-Options
It seems that when calling `init` and passing `advance_to_tstop = true` the behavior I'd expect is that `step!` should continue stepping to that tstop.  That's not what I seem to be getting from this example code here:

```
function bc_model(du,u,h,p,t)
  p0,q0,v0,d0,p1,q1,v1,d1,d2,beta0,beta1,tau = p
  hist3 = h(p, t-tau)[3]
  du[1] = (v0/(1+beta0*(hist3^2))) * (p0 - q0)*u[1] - d0*u[1]
  du[2] = (v0/(1+beta0*(hist3^2))) * (1 - p0 + q0)*u[1] +
          (v1/(1+beta1*(hist3^2))) * (p1 - q1)*u[2] - d1*u[2]
  du[3] = (v1/(1+beta1*(hist3^2))) * (1 - p1 + q1)*u[2] - d2*u[3]
end

h(p, t) = ones(3)

tau = 1
lags = [tau]

p0 = 0.2; q0 = 0.3; v0 = 1; d0 = 5
p1 = 0.2; q1 = 0.3; v1 = 1; d1 = 1
d2 = 1; beta0 = 1; beta1 = 1
p = (p0,q0,v0,d0,p1,q1,v1,d1,d2,beta0,beta1,tau)
tspan = (0.0,100.0)
u0 = [1.0,1.0,1.0]

prob = DDEProblem(bc_model,u0,h,tspan,p; constant_lags=lags)
int = init(prob, MethodOfSteps(Tsit5());tstops = [4.5], advance_to_tstop = true, save_everystep = false)

step!(int)
int.t
```

After calling `step!` the time is 1, rather than 4.5.

**Comment by devmotion** [comment]
I agree, that's surprising and unintuitive. By default, if constant lags are provided, the DDE solvers step to the propagated discontinuities arising from these lags (up to the order of the chosen algorithm) such that the interpolation between different time steps is guaranteed to be sufficiently smooth. This is achieved by adding the next propagated discontinuities to the list of time steps `integrator.opts.tstops` and the list of discontinuities `integrator.opts.d_discontinuities`. You can check that "1" is added to these by printing `int.opts.tstops` and `int.opts.d_discontinuities` after creating the integrator `int`. Hence actually the algorithm proceeds correctly to the next time step but unfortunately it was not specified by the user in this case.

I guess the easiest fix to this problem would be to save a heap of the original time steps in an additional field, and then use it for the check in https://github.com/SciML/DelayDiffEq.jl/blob/c45ed5af4c92a814281e90a399844e4947db814b/src/integrators/interface.jl#L514 instead of `integrator.opts.tstops` (we even already have `integrator.opts.tstops_cache` but that just saves the original time steps in whatever way they were provided but not as heap). What's your opinion on this, @ChrisRackauckas?

For now, as a workaround you could just not provide any lags at all (i.e., remove the `constant_lags` keyword argument) or (maybe better) specify them as dependent lags with the `dependent_lags` keyword arguments. Then `integrator.opts.tstops` is not modified internally.

**Comment by slwu89** [comment]
Thanks @devmotion, that's helpful to know. So the easy fix would be something like using `integrator.tdir * integrator.t < first(integrator.p.user_tstops)`. I'll use those workarounds for now.

**Comment by ChrisRackauckas** [comment]
>instead of integrator.opts.tstops (we even already have integrator.opts.tstops_cache but that just saves the original time steps in whatever way they were provided but not as heap). What's your opinion on this, @ChrisRackauckas?

Yeah I guess we need another because of the interaction between derivative propagation and tstops.

**Comment by slwu89** [comment]
Hi @ChrisRackauckas, just wondering if there was a plan to address this issue in the upcoming update schedule?

**Comment by devmotion** [comment]
Ah sorry, I had already experimented with a fix but then was busy with some other things and forgot about it. I'll try to fix it until the end of this week.

**Comment by slwu89** [comment]
Thanks @devmotion, excited to work with the library after this is done!
