### ISSUE TITLE
Call to HistoryFunction gets replaced by call to ODEFunction

### ISSUE THREAD

**Issue by lindnemi** [SciML/DelayDiffEq.jl#219]
I was trying to reproduce https://discourse.julialang.org/t/delay-differential-equations-networks-with-different-delay-per-edge/69787 in NetworkDynamics.jl and found a VERY weird behaviour. 

For large enough networks and after the history function got called a few dozen times, a seemingly random call to `h` triggers a call to `f` instead, resulting in an error.

I don't think the problem is with NetworkDynamics, since i can think of no way it could change the function body that `h` refers to and if the network is small (N <= 4) everything works as expected.

I tried to find a MWE without NetworkDynamics but was not able to do so, hence I am wondering if a sufficiently complex type system is required to trigger the bug.

:heavy_exclamation_mark: You will need a development branch of NetworkDynamics.jl to run the example: https://github.com/PIK-ICoNe/NetworkDynamics.jl/tree/hetero_delay 

```julia

using DelayDiffEq
using Random
using LightGraphs
using NetworkDynamics
using Distributions

N = 5
g = SimpleDiGraph(complete_graph(N))

function kuramoto!(dθ, θ, edges, p, t)
    ω = p
    dθ[1] = ω
    for e in edges
        dθ[1] += e[1]
    end
    return nothing
end

function delay_coupling(e, θ_s, θ_d, h, θ_s_idx, θ_d_idx, p, t)
    typeof(h) <: DelayDiffEq.HistoryFunction ? 
        display(DelayDiffEq.HistoryFunction) :
        display(typeof(h))
    display(p)
    τ, κ = p
    hist1 = h("WTF?", t - τ; idxs=θ_s_idx[1])
    hist1=θ_s[1]
    e[1] = κ * sin(hist1 - θ_d[1])
    return nothing
end

vertex = ODEVertex(f! = kuramoto!, dim = 1)
edge = StaticDelayEdge(f! = delay_coupling, dim=1, coupling=:directed)
nd = network_dynamics(vertex,edge,g)

Random.seed!(1)

ω = rand(nv(g))
τ = rand(ne(g))
κ = rand(ne(g))
p = (ω, [τ'; κ'])

θ₀ = rand(Uniform(0, 2π), N)

const past = rand(Uniform(0, 2π), N)
h(p, t; idxs=nothing) = past[idxs]

nd.f(ones(N), ones(N),h,p,0)

prob = DDEProblem(nd, θ₀, h, (0.0, 1.0), p, constant_lags=τ)

solve(prob, MethodOfSteps(BS3()), saveat=0.01, reltol=0, abstol=1e-5)
```

Output:
```
DelayDiffEq.HistoryFunction
2-element view(::Matrix{Float64}, :, 1) with eltype Float64:
 0.21096820215853596
 0.6448833539420931

[...]

DelayDiffEq.HistoryFunction
2-element view(::Matrix{Float64}, :, 12) with eltype Float64:
 0.25137920979222494
 0.4556920516275036
DelayDiffEq.HistoryFunction
2-element view(::Matrix{Float64}, :, 13) with eltype Float64:
 0.02037486871266725
 0.2793951106725605
typeof(h)
"WTF?"
```

If the bug does not reproduce at your machine right away, try increasing `N` to `10`. On Julia 1.6.2 `N = 4` works without issues and the bug appears at `N=5`, while on Julia 1.7.0-rc2 already `N>=4` fails. I added some display statements to illustrate that the type of `h` actually changes and so do the `parameters`. Apparently the input arguments for `h` are inserted into `f`.

**Comment by devmotion** [comment]
I am not familiar with NetworkDynamics and don't know if the observation is caused by the implementation there. A MWE with a simple system would be helpful.

However, in general it is not surprising and even expected that parameters and calls of the history function are sometimes forwarded to calls of the DDE model function. The evaluation of the history function in the model works as follows:
1. When you evaluate the history function in your model for time points prior to the initial time point it will evaluate the history function for these time points that you specified in the problem (https://github.com/SciML/DelayDiffEq.jl/blob/503dd2f8b1ca97e917a9c925925c7a82a1e6a0a9/src/history_function.jl#L26-L36)
2. When you evaluate the history function at a time point before the last integration step, the interpolation of the solution is evaluated (https://github.com/SciML/DelayDiffEq.jl/blob/503dd2f8b1ca97e917a9c925925c7a82a1e6a0a9/src/history_function.jl#L38-L41)
3. When you evaluate the history function at a time point in the current integration step or later, an extrapolation is evaluated (https://github.com/SciML/DelayDiffEq.jl/blob/503dd2f8b1ca97e917a9c925925c7a82a1e6a0a9/src/history_function.jl#L49-L54)

Now for instance, in the third case, `DiffEqBase.addsteps!` is called in e.g. https://github.com/SciML/OrdinaryDiffEq.jl/blob/696be8fc8c983018311d5a388eb5dd5cb1605a4c/src/dense/generic_dense.jl#L347 (called via  https://github.com/SciML/OrdinaryDiffEq.jl/blob/696be8fc8c983018311d5a388eb5dd5cb1605a4c/src/integrators/integrator_utils.jl#L401-L403  and `current_interpolant`) since some algorithms use specialized interpolations that require to compute intermediate integration steps. This leads to calls of the model function in e.g. https://github.com/SciML/OrdinaryDiffEq.jl/blob/696be8fc8c983018311d5a388eb5dd5cb1605a4c/src/dense/low_order_rk_addsteps.jl#L32.

The only surprising thing here is that it is caused with `BS3` which does use a standard Hermite interpolation. So I assume there is another (not necessarily incorrect) way of triggering the calls of the model.

**Comment by lindnemi** [comment]
Hello David,

thank you very much for the explanation, it is now much clearer to me what is happening. The lag time for which the error appears is very small, so probably it's a case 3 then.

What is very unexpected to me, is that the parameters passed to the history function are in fact the same parameters that the model function uses. I think this fact is nowhere documented. Instead, I was assuming that the history function parameters are used to define parameter dependent initial values. I would be curious to learn the reason why those have to be passed to the history function explicitly instead of being provided by the integrator.

**Comment by devmotion** [comment]
You define which parameters are passed to the evaluation of the history in your model definition. As you say, one common example is that the history prior to the initial time point is parameter dependent. You would then include these parameters in your model parameters.

It is not clear to me how it would be possible to pass parameters of the model function to the history function `h` automatically and let users write e.g. `h(t)` instead of `h(p, t)` in the model. Remember that, similar to the ODE models, it should be possible to just call `model([du, ], u, h, p, t)` and obtain the first-order derivatives of the model at time `t` with parameters `p` and history function `h` (has to be defined for all time points <= `t`). There is no guarantee that `p` matches some implicit parameters of `h` (and there is no generic way to update implicit, i.e. closed over, parameters), so the simplest and IMO only way to handle parameters in both the model and the history function is to pass `p` to `h` explicitly when calling  it in the function body of `model`.

**Comment by lindnemi** [comment]
I see, thank you for the explanation.

What I did so far is to call `h(p[1],t)` with only the parameters that are actually used by the history function. This leads to an error in case 3, since `h(p[1], t)` then results in `f(dx,x,h,p[1],t)` with only a subset of the necessary parameters. That's why i was wondering if it would be possible to use the full parameters `p` by default in case 3 [they should be wrapped in the integrator if i am not mistaken?].

For me calling `h(p[1], t)` or `h(p,t)` is not just a question of style, but NetworkDynamics is actually written in such a way that every component of the network sees only local parameters, e.g. `p[dim*i : dim*i+1]`. Since `h` is called within the component function there is no obvious way how the global parameters could be passed on. Of course there is always to possibility to change the ND component interface and make global information available within components.

**Comment by lindnemi** [comment]
I found a workaround by providing a function wrapper that inserts the correct parameters. Thanks again for your help.
